name: Waka Readme


on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC // 30 17 * * *
    - cron: '00 * * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "True" 
          SYMBOL_VERSION: 2
          COMMIT_BY_ME: "True"
         # LOCALE: "en"
